# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty

os:
  - linux

r:
- release

osx_image: xcode9

bioc_packages:
  - BiocCheck

env:
  global:
  - R_BUILD_ARGS="--no-manual"
  - R_CHECK_ARGS="--as-cran --install-args=--build"

before_install:
- export PACKAGE_NAME=`package_name`

script:
  - R CMD build ${R_BUILD_ARGS} .
  - R CMD BiocCheck ${PACKAGE_NAME}*.tar.gz --no-check-bioc-views

after_success:
  - Rscript -e 'covr::codecov()'

