# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty

os:
  - linux

r:
- release

osx_image: xcode9

bioc_packages:
  - BiocCheck

before_install:
- export PACKAGE_NAME=`package_name`

after_success:
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck ${PACKAGE_NAME}*.tar.gz
